---
- name: Deploy React Tasklist to AWS EC2
  hosts: tasklist_server
  become: yes
  vars:
    app_dir: /var/www/tasklist
    app_user: straumandi
    node_version: 20

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ app_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Add GitHub deploy key
      copy:
        content: "{{ lookup('env', 'REPO_DEPLOY_KEY') }}"
        dest: "/home/{{ app_user }}/.ssh/github_deploy_key"
        mode: '0600'
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Debug key format
      ansible.builtin.shell: |
        cat /home/{{ app_user }}/.ssh/github_deploy_key
      become: yes
      become_user: "{{ app_user }}"
      register: key_content

    - name: Display key format
      ansible.builtin.debug:
        var: key_content.stdout_lines

    - name: Debug - Check key existence
      stat:
        path: "/home/{{ app_user }}/.ssh/github_deploy_key"
      register: key_stat

    - name: Debug - Show key file info
      debug:
        msg: 
          - "Key exists: {{ key_stat.stat.exists }}"
          - "Key permissions: {{ key_stat.stat.mode }}"
          - "Key owner: {{ key_stat.stat.pw_name }}"

    - name: Debug - Check key content format
      shell: |
        head -n 1 /home/{{ app_user }}/.ssh/github_deploy_key
      register: key_header
      become: yes
      become_user: "{{ app_user }}"

    - name: Debug - Show key header
      debug:
        msg: "Key starts with: {{ key_header.stdout }}"

    - name: Debug - Test SSH connection
      shell: |
        ssh -Tv git@github.com
      register: ssh_test
      become: yes
      become_user: "{{ app_user }}"
      ignore_errors: yes

    - name: Debug - Show SSH test result
      debug:
        msg: "{{ ssh_test.stderr_lines }}"

    - name: Configure SSH for GitHub
      copy:
        content: |
          Host github.com
            IdentityFile /home/{{ app_user }}/.ssh/github_deploy_key
        dest: "/home/{{ app_user }}/.ssh/config"
        mode: '0600'
        owner: "{{ app_user }}"

    - name: Update dnf cache
      dnf:
        update_cache: yes
      when: ansible_distribution == 'Amazon'

    - name: Install required packages
      dnf:
        name:
          - nodejs
          - npm
          - git
          - python3-pip
        state: present

    - name: Ensure app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Add GitHub to known hosts
      known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        state: present
      become_user: "{{ app_user }}"

    - name: Pull latest code from repository
      git:
        repo: "git@github.com:straumandi/armanious_schmatz.git"
        dest: "{{ app_dir }}"
        version: main
        force: yes
        key_file: "/home/{{ app_user }}/.ssh/github_deploy_key"
      become_user: "{{ app_user }}"
      environment:
        GIT_SSH_COMMAND: "ssh -vvv" # Enable verbose output for debugging

    - name: Install app dependencies
      npm:
        path: "{{ app_dir }}"
        ci: yes
      become_user: "{{ app_user }}"

    - name: Copy environment file
      copy:
        content: |
          NODE_ENV=production
          PORT=3000
        dest: "{{ app_dir }}/.env"
        owner: "{{ app_user }}"
        mode: '0600'

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Start/restart application with PM2
      command: pm2 restart ecosystem.config.js --update-env
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"