---
- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_container:
        name: tasklist-react-app
        image: "${{ secrets.DOCKER_USERNAME }}/tasklist-react-app:latest"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
        pull: yes