---
- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}:{{ docker_tag }}"
        source: pull
        force_source: yes

    - name: Run Docker container
      docker_container:
        name: vite-react-app
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
        recreate: yes