name: Deploy to EC2

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Wait for instance setup
        run: |
          echo "Waiting for instance to complete setup..."
          sleep 30  # Wait 30 seconds for user_data script to complete

      - name: Set up SSH keys
        env:
          REPO_DEPLOY_KEY: ${{ secrets.REPO_DEPLOY_KEY }}
        run: |
          mkdir -p /home/runner/.ssh
          # Start ssh-agent
          eval $(ssh-agent -s)
          # Add the key to ssh-agent
          echo "$REPO_DEPLOY_KEY" | tr -d '\r' | ssh-add -

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/deploy.yml -vv
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
          REPO_DEPLOY_KEY: ${{ secrets.REPO_DEPLOY_KEY }}
