name: Deploy to EC2

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          # EC2 SSH key
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Repository deploy key
          echo "${{ secrets.REPO_DEPLOY_KEY }}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/github_deploy_key
          # Add known hosts
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: ansible-playbook -i ansible/inventory.yml ansible/deploy.yml
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          REPO_DEPLOY_KEY: ${{ secrets.REPO_DEPLOY_KEY }}
          ANSIBLE_HOST_KEY_CHECKING: false
