name: Deploy to EC2

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Set up SSH key
        run: |
          set -x  # Enable debug mode
          mkdir -p ~/.ssh || { echo "Failed to create .ssh directory"; exit 1; }
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa || { echo "Failed to write SSH key"; exit 1; }
          chmod 600 ~/.ssh/id_rsa || { echo "Failed to set permissions"; exit 1; }
          ssh-keyscan -H 52.57.97.250 >> ~/.ssh/known_hosts 2>&1 || { echo "Failed to scan host key"; exit 1; }
          ls -la ~/.ssh/id_rsa
          ssh -v -o StrictHostKeyChecking=no 52.57.97.250 'echo "SSH connection test"' || { echo "Failed to connect via SSH"; exit 1; }

      - name: Run Ansible playbook
        run: |
          ansible --version
          ansible-inventory --list -i ansible/inventory.yml
          ANSIBLE_DEBUG=1 ansible-playbook -i ansible/inventory.yml ansible/deploy.yml -vvv
        env:
          EC2_HOST: 52.57.97.250
          ANSIBLE_HOST_KEY_CHECKING: false
